/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_saycheeze_MainActivity */

#ifndef _Included_com_example_saycheeze_MainActivity
#define _Included_com_example_saycheeze_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_saycheeze_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define com_example_saycheeze_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     com_example_saycheeze_MainActivity
 * Method:    loadCascade
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_saycheeze_MainActivity_loadCascade
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_saycheeze_MainActivity
 * Method:    detect
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_saycheeze_MainActivity_detect
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);


#ifdef __cplusplus
}
#endif
#endif
